apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: davarski/k8s-demo-app-java:v1.0
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
          add: ["NET_ADMIN", "SYS_TIME"]
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
          
          
          
